<footer>
        
        <h3>BLUEMATRIX<br> THE TIDE OF INNOVATION </h3>
        <div class="footer-container">
            <div class="footer-section">
                <p>Helpdesk</p>
                <p><a href="#">Career Helpdesk</a></p>
                <p><a href="mailto:bluematrix2025@gmail.com">Email</a></p>
            </div>
            <div class="footer-section">
                <p>About Us</p>
                <p><a href="#">About Bluematrix</a></p>
                <p><a href="#">Media Gallery</a></p>
                <p><a href="#">Invest In Us</a></p>
            </div>
            <div class="footer-section">
                <p>Others</p>
                <p><a href="#">Blog</a></p>
                <p><a href="#">Our Activities</a></p>
            </div>
        </div>
    </footer>