
 <header>
        <nav>
            <ul>
                <li><a href="login.php">BLUEMATRIX</a></li>
                <li><a href="index.php" >HOME</a></li>
                <li><a href="jobs.php">JOBS</a></li>
                <li><a href="apply.php">APPLY</a></li>
                <li><a href="about.php">ABOUT</a></li>
                <li><a href="enhancements.php">ENHANCEMENTS</a></li>
            </ul> 
        </nav>
    </header>
